name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/gitActions
            git pull
            python3 main.py


#    - name: Checkout кода
#      uses: actions/checkout@v2
#
#    - name: Установка зависимостей
#      run: |
#        sudo apt-get update
#        sudo apt-get install python3 python3-pip python3-venv -y
#        python3 -m venv venv
#        source venv/bin/activate
#        pip install -r requirements.txt
#
#    - name: Сборка статических файлов
#      run: |
#        source venv/bin/activate
#        python manage.py collectstatic --noinput
#
#    - name: Применение миграций
#      run: |
#        source venv/bin/activate
#        python manage.py migrate --noinput
#
#    - name: Перезапуск Gunicorn
#      run: sudo systemctl restart gunicorn
